### ISSUE TITLE
Objective-C exception thrown.  Name: NSInternalInconsistencyException 

### ISSUE THREAD

**Issue by firelamb** [o1298098/Xamarin-CloudMusic#6]
sometimes will get the error：
Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

**Comment by o1298098** [comment]
Clean up CloudMusic.iOS and rebuild,it should work properly

**Comment by o1298098** [comment]
remove
```
#if DEBUG
            if (!HotReloader.Current.IsRunning)
                HotReloader.Current.Start(this);
#endif
```
at App.xaml.cs ,should work

**Comment by AndreiMisiukevich** [comment]
HotReloader.Current.Run(this) with latest version
