### ISSUE TITLE
API Connection Problem

### ISSUE THREAD

**Issue by serkanodaci** [o1298098/Xamarin-CloudMusic#9]
Api gives the error "{"msg":"年轻人 自己搭API吧~","code":200}".
Can you share Api code with us?

**Comment by o1298098** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi
you can find the api here. maybe I build the api service later

**Comment by o1298098** [comment]
you can use this apihost http://104.207.135.233:3000

**Comment by serkanodaci** [comment]
Thank you very much for your support
